 const SET_ALERT = 'SET_ALERT';
 const REMOVE_ALERT = 'REMOVE_ALERT';
 const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
 const REGISTER_FAIL = 'REGISTER_FAIL';
 const USER_LOADED = 'USER_LOADED';
 const AUTH_ERROR = 'AUTH_ERROR';
 const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
 const LOGIN_FAIL = 'LOGIN_FAIL';
 const LOGOUT = 'LOGOUT';
 const GET_PROFILE = 'GET_PROFILE';
 export {USER_LOADED, SET_ALERT, AUTH_ERROR, REMOVE_ALERT, LOGOUT, LOGIN_SUCCESS, LOGIN_FAIL, GET_PROFILE, REGISTER_FAIL, REGISTER_SUCCESS}

